@startuml
'https://plantuml.com/sequence-diagram
autonumber

actor "客户端" as User #red
' The only difference between actor
'and participant is the drawing
participant "文件系统" as File #yellow
participant "id系统" as Uid #gray
participant "vienna" as Vienna #orange
participant "jdOss" as JdOss #gray
/' You can also declare:
   participant L as "I have a really\nlong name"  #99FF99
  '/
User -> Vienna : 申请 token
Vienna -> Uid : 申请 photo id
Uid --> Vienna : 返回 photo id
Vienna -> Vienna : 生成 key
Vienna -> JdOss : 申请 url=token
JdOss --> Vienna : url 中包含业务信息
Vienna --> User : 返回有效 url


User -> Vienna : 主动触发 callback .
Vienna -> File : 生成 upload_file
@enduml
