// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demoservice.proto

package com.ysz.dm.dubbo3.demo;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:demoservice.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
